export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "coral", padding: "10px", textAlign: "center" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "gray",
          padding: "10px",
          textAlign: "center",
          
          
        }}> <p>Footer</p></footer>
        </body>
    </html>
  )
}
